### ISSUE TITLE
在mac上编译不过的问题

### ISSUE THREAD

**Issue by Autumn1992** [cloudwu/ejoy3d#3]
你好。云风 ，我想问下 在Mac下编译会提示 ld: library not found for -lopengl32  有什么办法可以解决 网上查找好像opengl库又是随着xcode下载包含进里面了的。 编译出错就一脸懵逼了。

**Comment by cloudwu** [comment]
我不用 mac, 自己解决。

**Comment by Autumn1992** [comment]
噢 谢谢。 再多问句 这个Demo的默认编译平台是Linux or Win
